---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  # project: pipeline
  source:
    repoURL: "https://github.com/kostis-codefresh/argo-rollouts-istio-hpa"
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: pipeline-prod-test
  syncPolicy:
    retry:
      limit: 1
    syncOptions:
      - PruneLast=true
      - PrunePropagationPolicy=background
      - ApplyOutOfSyncOnly=true